"""
This script is a KMeans algorithm.

The KMeans algorithm in this script is one that is made without the use of
a machine learning library.  However, it does use pandas and numpy.

KMeans is an algorithm that creates K clusters in the data.  Data points
that are similar to each other generally fall within the same clusters.
This is useful when determining the likeness of data and can be used to group
different classes if abstracted at a higher level.  For instance you could
get features from a Convolution Neural Network that was trained on different
boats.  You then could use the KMeans algorithm on those features and then
determine which boats are similar to each other and create a list of them.

This is essentially how one can whitelist or blacklist boats for security 
reasons.
"""
import pandas as pd
import numpy as np


def generate_centroids(inital_dataframe, k):
    """
    Generate the centroids to be used as the center of the clusters.

    This method will randomly make k values ranging from the minimum value
    of the data to the maximum value ofthe data.  This places them in locations
    where the data can begin to be assigned to each cluster.

    Parameters
    ----------
    initial_dataframe : DataFrame
        A pandas DataFrame object that has been loaded with the intial data
        from a data source.

    k : int
        The K part of KMeans which is how many clusters will be created in
        the dataset.

    Returns
    -------
    centroid_frame : DataFrame
        A pandas DataFrame objec that holds the centroid data points that have
        been generated by this method.

    """
    df = inital_dataframe.iloc[:, 0:inital_dataframe.shape[1]-1]
    centroid_frame = pd.DataFrame(np.random.randint(df.values.min(),
                                  df.values.max(),
                                  size=(k, inital_dataframe.shape[1])))

    return centroid_frame


def shift_centroids(centroids, dataframe):
    """
    Generate new centroids with the mean of the clusters.

    This method will shift the centroids to the mean of each cluster.

    Parameters
    ----------
    centroids : DataFrame
        This is a pandas DataFrame object that holds the previous centroid
        points.

    dataframe : DataFrame
        This is a pandas DataFrame object that hold the dataset along with
        the clusters each data point belongs too.

    Returns
    -------
    copy_centroids : DataFrame
        This is a pandas DataFrame object that holds the new centroid location
        for each cluster.

    """
    copy_centroids = centroids.copy()

    for i in range(0, copy_centroids.shape[0]):
        # This is a boolean way to get only the values from the real frame for
        # each cluster
        df = dataframe[dataframe[dataframe.columns[-1]] == i]

        # shorten it so we dont get categorical data now.
        df = df.iloc[:, 0:dataframe.shape[1]-1]

        # add in the previous centroid for calculation
        df = df.append(copy_centroids.iloc[i])

        # do the calculation and the reset the centroid
        copy_centroids.iloc[i] = df.mean()

    return copy_centroids


def kMeans(initial_dataframe, k=3, epsilon=.1):
    """
    Run the KMeans algorithm.

    This method is the main method to running the KMeans algorithm.  It
    loops until the distance between the previous centroids and the current
    centroids change less that the epsilon value.

    Parameters
    ----------
    initial_dataframe : DataFrame
        This is a pandas DataFrame that holds the inital data from the dataset.
        In other words it is the data that is in the dataset file.

    k : int (default = 3)
        The K part of KMeans, this is an arbitrary value that is used to
        generate K amount clusters.

    epsilon : float (default = .1)
        This is the value that the distance between the previous centroids
        and the newly shifted centroids must be under for the algorithm to 
        stop.  If the distance is lower than this value then the algorithm is
        supposedly done and can't shift again.

    Returns
    -------
    data : Dataframe
        This is the pandas data object that has the data points

    """
    centroids = generate_centroids(initial_dataframe, k)

    frame_without_cluster_class = initial_dataframe.copy()   

    initial_dataframe['cluster'] = np.NaN

    while True:
        # assigning clusters to every point in the dataset
        # remember that you must have only numerical values when doing the
        # distance
        for index, point in frame_without_cluster_class.iterrows():
            distances = []
            for centroid_index, centroid in centroids.iterrows():
                distance = np.linalg.norm(point - centroid)
                distances.append(distance)
                # I know that the index of the distances will be the same as
                # the index in the centroid frame.  This is because there can
                # only be as many distances each point can have that there are
                # centroids
            cluster_assignment = distances.index(min(distances))
            # Have to use iloc and seperate by comma because this is the
            # assignment operation and not the view operation [] []
            data.iloc[index, data.shape[1]-1] = cluster_assignment

            # We need to shift the centroids
        new_centroids = shift_centroids(centroids, data)
        print(np.linalg.norm(new_centroids - centroids))
        if np.linalg.norm(new_centroids - centroids) <= epsilon:
            return data
        else:
            centroids = new_centroids


if __name__ == "__main__":
    data = pd.read_csv("iris.csv", header=None, delim_whitespace=True)

    print(kMeans(data, 8, .1))
